name: taesongkim
favicon: null
layout_spectrum: 0.91725
typography_spectrum: 0.79903
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#29272a'
    - '#a2a5b8'
    - '#84899d'
    - '#515465'
    - '#c4c6d3'
  brandStrength: 0.1875
  lightness: 0.9375
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
